# Generated by Django 5.0.3 on 2024-03-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_customer_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.PositiveIntegerField(default=0)),
                ('teachers', models.PositiveIntegerField(default=0)),
                ('staffs', models.PositiveIntegerField(default=0)),
                ('registrations', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
