# Generated by Django 5.0.3 on 2024-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='registrations',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stats',
            name='staffs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stats',
            name='students',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stats',
            name='teachers',
            field=models.CharField(max_length=20),
        ),
    ]
