# Generated by Django 5.0.3 on 2024-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_postnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnews',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
