# Generated by Django 5.0.3 on 2024-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_postnews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnews',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='postnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
