# Generated by Django 5.0.3 on 2024-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_postnews_images_alter_postnews_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media_images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
