# Generated by Django 5.0.3 on 2024-03-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url_drive',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
