# Generated by Django 5.0.3 on 2024-03-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_page_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
