# Generated by Django 4.2.13 on 2024-05-30 02:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_program_penanggung_jawab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename_image),
        ),
    ]
