# Generated by Django 4.2.13 on 2024-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_page_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
