# Generated by Django 4.2.13 on 2024-05-30 12:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename_image),
        ),
        migrations.AlterField(
            model_name='buku',
            name='ISBN',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
