# Generated by Django 4.2.13 on 2024-06-05 02:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_buku_images_alter_buku_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=accounts.models.rename_image)),
                ('judul', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
